/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package example

import kotlin.test.Test
import kotlin.test.assertNull

class AppTest {
    @Test fun example() {
        assertNull(null);
    }
}
